kubectl delete clusterrole neuvector-binding-app
kubectl delete clusterrole neuvector-binding-rbac
kubectl delete clusterrolebinding neuvector-binding-app
kubectl delete clusterrolebinding neuvector-binding-rbac
kubectl delete clusterrole neuvector-binding-admission
kubectl delete clusterrolebinding neuvector-binding-admission
kubectl delete clusterrole neuvector-binding-customresourcedefinition
kubectl delete clusterrolebinding  neuvector-binding-customresourcedefinition
kubectl delete clusterrole neuvector-binding-nvsecurityrules
kubectl delete clusterrolebinding neuvector-binding-nvsecurityrules
kubectl delete clusterrolebinding neuvector-binding-view
kubectl delete rolebinding neuvector-admin -n neuvector
kubectl delete clusterrole neuvector-binding-nvwafsecurityrules
kubectl delete clusterrolebinding neuvector-binding-nvwafsecurityrules
kubectl delete clusterrole neuvector-binding-nvadmissioncontrolsecurityrules
kubectl delete clusterrolebinding neuvector-binding-nvadmissioncontrolsecurityrules
kubectl delete clusterrole neuvector-binding-nvdlpsecurityrules
kubectl delete clusterrolebinding neuvector-binding-nvdlpsecurityrules
